FROM golang:1.22.5-alpine3.19
RUN mkdir /app
ADD . /app/
WORKDIR /app
# setup requirements
RUN apk add --no-cache git gcc musl-dev libc-dev
RUN go mod download
RUN go build -o main ./...
CMD ["/app/main"]
