services:
  app:
    build: .
    command: yarn dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
    env_file:
      - .env.local

networks:
  app-network:
    external: true
    name: backend_app-network
