version: '3.3'
services:
  app-new:
    command: ['./server', '${MODE}']
    build:
      context: ./app
    ports:
      - 80:80
      - 8081:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
